CREATE TABLE LINKS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    URL VARCHAR(255) NOT NULL,
    NOTES VARCHAR(255)
);

CREATE TABLE TAGS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    LINK_ID INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    FOREIGN KEY (LINK_ID) REFERENCES LINKS(ID) ON DELETE CASCADE
);

CREATE TABLE TAG_NAMES (
    NAME VARCHAR(255) PRIMARY KEY
);