CREATE TABLE LINKS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    URL VARCHAR(255) NOT NULL,
    TAGS VARCHAR(255) ARRAY NOT NULL,
    NOTES VARCHAR(255)
);

CREATE TABLE TAG_NAMES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE INDEX idx_tag_name ON TAG_NAMES (NAME);